//Criando um novo evento.
POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Evento Estudar 2",         
  "details": "Um evento inovador!!",       
  "maximumAttendees": 1
}

###
// Registrando um participante em um evento.
POST http://localhost:3333/events/58e1a22b-200a-4d05-87d0-cc9287ff4100/attendees
Content-Type: application/json

{
  "name": "Matheus Wesley",         
  "email": "matheuswesley2@email.com"
}