//Criando um novo evento.
POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Evento Estudar 2",         
  "details": "Um evento inovador!!",       
  "maximumAttendees": 1
}

###
// Registrando um participante em um evento.
POST http://localhost:3333/events/a860b770-ea51-4a0f-9903-c84b9109bde4/attendees
Content-Type: application/json

{
  "name": "Math",         
  "email": "math@email.com"
}

###
// Consultando um evento
GET http://localhost:3333/events/58e1a22b-200a-4d05-87d0-cc9287ff4100


// Consultando o cartão do participante
###
GET http://localhost:3333/attendees/1/badge